[package]
name = "RBC_rust"
version = "0.1.0"
authors = ["Marcello Seri <marcello.seri@gmail.com>"]

[dependencies]
time = "0.1"

[[bin]]
name = "testrust"

[[bin]]
name = "restrustunsafe"
path = "src/main1.rs"